name: DonutSpawners
version: 1.0.0
main: net.donutsmp.spawners.DonutSpawners
api-version: 1.21
depend: [Essentials]
commands:
  givespawner:
    description: Give a spawner to a player
    usage: /givespawner <player> <type> [stack]
    permission: donutspawners.admin
permissions:
  donutspawners.admin:
    default: op
    description: Admin permission for DonutSpawners
